theme = "gruvbox-dark"
icons = "awesome5"



[[block]]
block = "memory"
clickable = false
warning_mem = 70.0
critical_mem = 80.0
format_mem = "{MFg}GB/{MTg}GB"

[[block]]
block = "cpu"
interval = 10
per_core = false
format = "{frequency}"


[[block]]
block = "load"
format = "{1m} {5m} {15m}"


[[block]]
block = "pacman"
interval = 10
format = "{pacman}"
hide_when_uptodate = true


[[block]]
block = "sound"
max_vol = 100
on_click = "amixes set Master toggle"


[[block]]
block = "battery"
device = "BAT1"
format = "{percentage}%"
full_format = "FULL"
info = 70
good = 60
warning = 40
critical = 30


[[block]]
block = "time"
format = "%d/%m %R"
